windows:
  hosts:
    10.0.5.5:
      hostname: DC-BLUE10
      domain_name: blue10.local
      netbios_name: BLUE
      dhcp_name_server: 10.0.5.2
      ou_name: BLUE10
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_user: deployer
    csv_file: characters.csv
    ou_users_path: "OU=BLUE10,DC=blue10,DC=local"
    ou_groups_path: "OU=Groups,OU=Accounts,OU=BLUE10,DC=blue10,DC=local"
    password_csv_path: "/home/jake/Desktop/characters-passwords.csv"
    temp_password_file: "C:\\temp_passwords.csv"