- name: Ubuntu wazuh server stage 2 # Wazuh depends on static IPV4, so wazuh-server-playbook-1.yml must be run first.
  hosts: wazuhsrv2
  tasks:

    - name: Update apt cache # updates repos
      apt:
        update_cache: yes
      become: yes

    - name: Install prerequisites # necessary prereqs for Wazuh server
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
        state: present
      become: yes

    - name: Download Wazuh installation script # uses curl to get official install script
      get_url:
        url: https://packages.wazuh.com/4.3/wazuh-install.sh
        dest: /tmp/wazuh-install.sh
        mode: '0755'

    - name: Run Wazuh installation script (non-interactive) # runs the script to install wazuh
      ansible.builtin.shell: bash /tmp/wazuh-install.sh -a -i #a installs all components, i ignores compatibility checks
      args:
        creates: /var/ossec/bin/wazuh-control
      register: wazuh_install
      become: yes
      
    - name: Display installation results # outputs result of install script from terminal to user
      debug:
        var: wazuh_install.stdout_lines
      when: wazuh_install.changed

    - name: Change Wazuh admin password # Wazuh creates random long complex passwords by default, so this gets hardcoded password from wazuh-server-inventory.yml
      ansible.builtin.shell: |
        cd /usr/share/wazuh-indexer/plugins/opensearch-security/tools/
        ./wazuh-passwords-tool.sh -u admin -p "{{ wazuh_admin_pass }}"
      become: yes
      when: wazuh_install.changed