- name: Join Windows to Domain using WinRM
  hosts: win10
  gather_facts: no

  vars_prompt:
    - name: domain_admin_password
      prompt: "Enter domain admin password"
      private: yes

  tasks:
    - name: Set new hostname
      win_hostname:
        name: "{{ hostname }}"
      register: hostname_result

    - name: Reboot after hostname change
      win_reboot:
      when: hostname_result.reboot_required

    - name: Join the domain
      win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_admin }}@{{ domain_name }}"
        domain_admin_password: "{{ domain_admin_password }}"
        state: domain
      register: domain_join
      
    - name: Reboot after domain join
      win_reboot:
      when: domain_join.changed